FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}
ENV PYTHONPATH="/opt/python"

COPY pyproject.toml uv.lock ${LAMBDA_TASK_ROOT}/

RUN pip install --upgrade pip \
    && pip install --no-cache-dir uv \
    && uv export --format requirements-txt --frozen --no-dev --no-hashes --no-emit-project --no-emit-package opencv-python -o requirements.txt \
    && uv pip install --system --no-cache --no-deps --torch-backend cpu -r requirements.txt \
    && uv pip install --system --no-deps "onnx>=1.16,<2" "onnx2torch>=1.5.15" ml_dtypes

COPY shared_layer/python /opt/python

COPY lambda_function.py \
    ${LAMBDA_TASK_ROOT}

CMD ["lambda_function.lambda_handler"]
